-- forkIO :: IO () → IO ThreadId
-- Starts an action in a new lightweight thread (green thread) and returns its identifier.
-- killThread :: ThreadId → IO ()
-- Finishes a thread started with forkIO.
-- newMVar :: a → IO (MVar a)
-- Creates a synchronized mutable variable (MVar) with an initial value.
-- takeMVar :: MVar a → IO a
-- Reads and locks the MVar until it has a value, leaving it empty.
-- putMVar :: MVar a → a → IO ()
-- Writes to an MVar; if it is full, blocks until it becomes empty.
-- newIORef :: a → IO (IORef a)
-- Creates a non-blocking mutable reference.
-- readIORef :: IORef a → IO a
-- Reads the value of the reference.
-- writeIORef :: IORef a → a → IO ()
-- Writes a value to the reference.
