name: Test

"on":
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

permissions:
  contents: read

jobs:
  validate:
    uses: ./.github/workflows/build.yml
    with:
      package: true
